server:
  port: 9090

spring:
  application:
    name: msvc-course
  config:
    import: optional:configserver:http://localhost:8888 #configuracion provisional del servicio config

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_course
    username: root
    password: admin1234
  jpa:
    hibernate:
      ddl-auto: create #para que me crea las tablas al momento de levantar el servicio
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

#Registra el servicio al Eureka
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka